# -*- coding: utf-8 -*-
"""Fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3Cay81CKg0ZpXMIvs7JkhT9aYLVU_ML
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Datasets/AIML Dataset.csv")

df.columns

"""*   ***step***: Represents a unit of time in the real world (1 step is 1 hour). It denotes the portion of the time period the transaction occurredList item
*   ***nameOrig***:  unique ID of sender      
* ***oldbalanceOrg***: The initial balance of the sender before the transaction
* ***newbalanceOrig***: The new balance of the sender after the transaction
* ***nameDest***: The unique ID of the recipient account.      
* ***oldbalanceDest***: The initial balance of the recipient before the transaction
* ***newbalanceDest***: The new balance of the recipient after the transaction
* ***isFraud***: The target variable for your model. A value of 1 indicates a fraudulent transaction, while 0 indicates it is legitimate
* ***isFlaggedFraud***: A flag set by the existing system to mark suspicious activity, typically for large transfers (e.g., over 200,000 units)


"""

df.isnull().sum()

df.head()

df.info()

df.duplicated().sum()

df.shape

print(df["isFraud"].value_counts())
print(df["isFlaggedFraud"].value_counts())

round((df['isFraud'].value_counts()[1] / df.shape[0]) * 100,2)
# the percentage of fruad trasaction in our dataset.
# no. of fraud transaction / total transaction * 100

import matplotlib.pyplot as plt

df['type'].value_counts().plot(kind='bar', title='Transaction types')
plt.xlabel('Transaction Type')
plt.ylabel('Count')
plt.show()

frud_by_type = df.groupby('type')['isFraud'].mean()
print(frud_by_type)
#which type of trasaction is seen mainly in fraud

df['amount'].describe().astype(int)
#statistical values of amount

import seaborn as sns
sns.boxplot(x='isFraud', y='amount', data=df[df['amount'] < 50000])
plt.show()
#the relation b/w  amount and fraud

df['diffsender'] = df['oldbalanceOrg'] - df['newbalanceOrig']
df['diffreceiver'] = df['oldbalanceDest'] - df['newbalanceDest']
#to check the anomalities and balance chain

print((df['diffsender'] < 0).sum())
print((df['diffreceiver'] < 0).sum())
#we have multiple negetive values in our sender and reciver diffrenced.

df.groupby(df['diffsender'] < 0)['isFraud'].mean()

df.groupby(df['diffreceiver'] < 0)['isFraud'].mean()

"""Sender and receiver balance differences showed that negative sender differences were not associated with fraudulent transactions, while negative receiver differences showed only a marginal increase in fraud rate."""

fraud_per_step = df[df['isFraud'] == 1]['step'].value_counts().sort_index()
plt.plot(fraud_per_step.index, fraud_per_step.values)
plt.xlabel('Step')
plt.ylabel('Number of Fraudulent Transactions')
plt.title('Number of Fraudulent Transactions per Step')
plt.show()

df[['step', 'isFraud']].corr()

"""Fraud occurrence varies across transaction steps, indicating that fraudulent activities are not uniformly distributed over time"""

import matplotlib.pyplot as plt
import seaborn as sns

# Correlation matrix
corr_matrix = df.select_dtypes(include=['number']).corr()

# Plot heatmap
plt.figure(figsize=(12,8))

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt='.2f',
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')

plt.show()

df['isFraud'].value_counts()



df.head()

df.drop(columns=['nameOrig', 'nameDest', 'isFlaggedFraud'], inplace=True)

df.head()

x = df.drop(columns=['isFraud'])
y = df['isFraud']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

categorical_cols = ['type']

numerical_cols = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest', 'diffsender', 'diffreceiver']

preprocessor = ColumnTransformer(transformers=[('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols),
        ('num', StandardScaler(), numerical_cols)])

x_train_processed = preprocessor.fit_transform(x_train)
x_test_processed = preprocessor.transform(x_test)

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

x_train_smote, y_train_smote = smote.fit_resample(x_train_processed, y_train)

x_train_smote

print(y_train.value_counts())

print(y_train_smote.value_counts())

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

model.fit(x_train_smote, y_train_smote)

y_pred = model.predict(x_test_processed)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

model.score(x_test_processed, y_test)

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import average_precision_score

# No SMOTE needed — XGBoost handles it via scale_pos_weight
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', XGBClassifier(
        scale_pos_weight=6354407/8213,
        n_estimators=300,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric='aucpr'
    ))
])

pipeline.fit(x_train, y_train)
y_pred_proba = pipeline.predict_proba(x_test)[:, 1]
print(f"PR-AUC: {average_precision_score(y_test, y_pred_proba):.4f}")

y_pred = pipeline.predict(x_test)

confusion_matrix(y_test, y_pred)

pipeline.score(x_test, y_test)

print(classification_report(y_test, y_pred))

import numpy as np
from sklearn.metrics import precision_recall_curve

y_probs = pipeline.predict_proba(x_test)[:, 1]

precision, recall, thresholds = precision_recall_curve(y_test, y_probs)

f1_scores = (2 * precision * recall) / (precision + recall + 1e-9)

best_idx = np.argmax(f1_scores)
best_threshold = thresholds[best_idx]

print("Best Threshold:", best_threshold)
print("Best F1:", f1_scores[best_idx])

y_pred_opt = (y_probs >= best_threshold).astype(int)

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred_opt))
print(classification_report(y_test, y_pred_opt))

from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

xgb = XGBClassifier(
    scale_pos_weight=6354407/8213,
    eval_metric='aucpr',
    random_state=42
)

param_grid = {
    'n_estimators': [200, 300, 500],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0]
}

pipeline_tuned = Pipeline([
    ('preprocessor', preprocessor),
    ('model', xgb)
])

import joblib

joblib.dump(pipeline, 'fraud_model.pkl')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # Load model
# model = joblib.load('fraud_model.pkl')
# 
# st.title("Fraud Detection App")
# 
# st.write("Enter transaction details:")
# 
# # User Inputs
# step = st.number_input("Step", min_value=0)
# 
# transaction_type = st.selectbox(
#     "Transaction Type",
#     ['CASH_IN', 'CASH_OUT', 'DEBIT', 'PAYMENT', 'TRANSFER']
# )
# 
# amount = st.number_input("Amount", min_value=0.0)
# 
# oldbalanceOrg = st.number_input("Old Balance Origin", min_value=0.0)
# 
# newbalanceOrig = st.number_input("New Balance Origin", min_value=0.0)
# 
# oldbalanceDest = st.number_input("Old Balance Destination", min_value=0.0)
# 
# newbalanceDest = st.number_input("New Balance Destination", min_value=0.0)
# 
# # Feature engineering
# diffsender = newbalanceOrig - (oldbalanceOrg - amount)
# 
# diffreceiver = newbalanceDest - (oldbalanceDest + amount)
# 
# # Prediction button
# if st.button("Predict Fraud"):
# 
#     input_data = pd.DataFrame({
#         'step': [step],
#         'type': [transaction_type],
#         'amount': [amount],
#         'oldbalanceOrg': [oldbalanceOrg],
#         'newbalanceOrig': [newbalanceOrig],
#         'oldbalanceDest': [oldbalanceDest],
#         'newbalanceDest': [newbalanceDest],
#         'diffsender': [diffsender],
#         'diffreceiver': [diffreceiver]
#     })
# 
#     prediction = model.predict(input_data)[0]
# 
#     probability = model.predict_proba(input_data)[0][1]
# 
#     if prediction == 1:
#         st.error(f"Fraud Detected! Probability: {probability:.2f}")
#     else:
#         st.success(f"Legitimate Transaction. Probability: {probability:.2f}")

!pip install streamlit

!pip install pyngrok

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

ngrok.set_auth_token("3E6sSWRyiHPFgiV4MyAKhY9rtgb_5DSshUis1i8Dmc7HfnQRV")

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

public_url = ngrok.connect(8501)

print(public_url)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# scikit-learn
# xgboost
# joblib

from google.colab import files

files.download('app.py')
files.download('fraud_model.pkl')
files.download('requirements.txt')